apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: install component
inputs:
  version:  
    description: component version or image tag
    required: true
outputs: 
runs:
  using: composite
  steps:
    - name: Install component
      uses: docker://alpine:3.17
      run: echo installing component "${{ github.repository }}" version "${{ inputs.version }}"
